// <auto-generated />
using System;
using Entrenate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entrenate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EntrenateDbContext))]
    [Migration("20260902163908_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entrenate.Domain.Entidades.DiaRutina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("RutinaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId", "Orden")
                        .IsUnique();

                    b.ToTable("DiasRutina", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Equipamiento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GrupoMuscularPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImagenPrincipalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("WorkoutGuideId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutGuideId")
                        .IsUnique();

                    b.ToTable("Ejercicios", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.EjercicioRutina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadSeries")
                        .HasColumnType("integer");

                    b.Property<int>("DescansoSegundos")
                        .HasColumnType("integer");

                    b.Property<Guid>("DiaRutinaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RepeticionesMaximas")
                        .HasColumnType("integer");

                    b.Property<int>("RepeticionesMinimas")
                        .HasColumnType("integer");

                    b.Property<int>("RirObjetivoMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("RirObjetivoMinimo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("DiaRutinaId", "Orden")
                        .IsUnique();

                    b.ToTable("EjerciciosRutina", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.EjercicioSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DescansoObjetivoSegundos")
                        .HasColumnType("integer");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RepeticionesMaximasObjetivo")
                        .HasColumnType("integer");

                    b.Property<int>("RepeticionesMinimasObjetivo")
                        .HasColumnType("integer");

                    b.Property<int>("RirObjetivoMaximo")
                        .HasColumnType("integer");

                    b.Property<int>("RirObjetivoMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesObjetivo")
                        .HasColumnType("integer");

                    b.Property<Guid>("SesionEntrenamientoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("SesionEntrenamientoId", "Orden")
                        .IsUnique();

                    b.ToTable("EjerciciosSesion", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.PerfilEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AlturaCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("DiasDisponiblesSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DuracionSesionDeseadaMinutos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NivelExperiencia")
                        .HasColumnType("integer");

                    b.Property<int>("ObjetivoPrincipal")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoCorporalKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("Sexo")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilesEntrenamiento", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.Rutina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.SerieEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EjercicioSesionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("integer");

                    b.Property<decimal>("Peso")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer");

                    b.Property<int?>("Rir")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioSesionId", "NumeroSerie")
                        .IsUnique();

                    b.ToTable("SeriesEntrenamiento", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.SesionEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiaRutinaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiaRutinaId");

                    b.HasIndex("UsuarioId", "Fecha");

                    b.ToTable("SesionesEntrenamiento", (string)null);
                });

            modelBuilder.Entity("Entrenate.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.DiaRutina", b =>
                {
                    b.HasOne("Entrenate.Domain.Entidades.Rutina", "Rutina")
                        .WithMany("Dias")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.EjercicioRutina", b =>
                {
                    b.HasOne("Entrenate.Domain.Entidades.DiaRutina", "DiaRutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaRutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entrenate.Domain.Entidades.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaRutina");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.EjercicioSesion", b =>
                {
                    b.HasOne("Entrenate.Domain.Entidades.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entrenate.Domain.Entidades.SesionEntrenamiento", "SesionEntrenamiento")
                        .WithMany("Ejercicios")
                        .HasForeignKey("SesionEntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("SesionEntrenamiento");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.SerieEntrenamiento", b =>
                {
                    b.HasOne("Entrenate.Domain.Entidades.EjercicioSesion", "EjercicioSesion")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EjercicioSesion");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.SesionEntrenamiento", b =>
                {
                    b.HasOne("Entrenate.Domain.Entidades.DiaRutina", "DiaRutina")
                        .WithMany()
                        .HasForeignKey("DiaRutinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiaRutina");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entrenate.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entrenate.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entrenate.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entrenate.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.DiaRutina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.EjercicioSesion", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.Rutina", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("Entrenate.Domain.Entidades.SesionEntrenamiento", b =>
                {
                    b.Navigation("Ejercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
